name: Solar-system

on: 
    
    push:
        branches:
        - main
        - features

    workflow_dispatch:

env:
  MONGO_URI: 'mongodb+srv://supercluster.d83jj.mongodb.net/superData'
  MONGO_USERNAME: ${{ vars.MONGO_USERNAME }}
  MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}


jobs:
    Unit-testing:

        name: Unit testing
        strategy:
             matrix:
                  nodejs_version: [18,20]
                  os: [ubuntu-latest]
                  exclude:
                     - nodejs_version: 18
                       os: macos-latest
        runs-on: ${{ matrix.os }}
        steps:
            - name: checkout Repoistory
              uses: actions/checkout@v4
            
            - name: Install Node js version 18
              uses: actions/setup-node@v3
              with:
                node-version: ${{ matrix.nodejs_version }}

            - name: Install Dependencies
              run: npm install

            - name: Testing
              run: npm test

            - name: Archive Test result
              uses: actions/upload-artifact@v4
              with: 
                name: Test result
                path: test-results.xml
                

    Code-coverage:

      name: Code coverage
      runs-on: ubuntu-latest
      steps:
            - name: checkout Repoistory
              uses: actions/checkout@v4
            
            - name: Install Node js version 18
              uses: actions/setup-node@v3
              with:
                node-version: 18

            - name: Install Dependencies
              run: npm install

            - name: Code coverage
              continue-on-error: true
              run: npm run coverage

            - name: Archive Code coverage
              uses: actions/upload-artifact@v4
              with: 
                name: Code Coverage result
                path: coverage
                retention-days: 5

           



            
        
