name: Solar-system

on: 
    
    push:
        branches:
        - main
        - features

    workflow_dispatch:

env:
  MONGO_URI: 'mongodb+srv://supercluster.d83jj.mongodb.net/superData'
  MONGO_USERNAME: ${{ vars.MONGO_USERNAME }}
  MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}


jobs:
    Unit-testing:


        name: Unit testing
        strategy:
             matrix:
                  nodejs_version: [18,20]
                  os: [ubuntu-latest]
        runs-on: ${{ matrix.os }}
        steps:
            - name: checkout Repoistory
              uses: actions/checkout@v4
            
            - name: Install Node js version 18
              uses: actions/setup-node@v3
              with:
                node-version: ${{ matrix.nodejs_version }}

            - name: Cache Dependencies
              uses: actions/cache@v3
              with:
                path: node-modules
                key: ${{ runner.os }}-node-modules-${{  hashFiles('package.json') }}


            - name: Install Dependencies
              run: npm install

            - name: Testing
              run: npm test

                

    Code-coverage:
      
      name: Code coverage
      runs-on: ubuntu-latest
      steps:
            - name: checkout Repoistory
              uses: actions/checkout@v4
            
            - name: Install Node js version 18
              uses: actions/setup-node@v3
              with:
                  node-version: 18

            - name: Cache Dependencies
              uses: actions/cache@v3
              with:
                path: node-modules
                key: ${{ runner.os }}-node-modules-${{  hashFiles('package.json') }}    

            - name: Install Dependencies
              run: npm install

            - name: Code coverage
              continue-on-error: true
              run: npm run coverage

            - name: Archive Code coverage
              uses: actions/upload-artifact@v4
              with: 
                name: Code Coverage result
                path: coverage
                retention-days: 5

    docker:
       
       name: Containerisation
       needs: [Unit-testing, Code-coverage]
       permissions:
            packages: write
       runs-on: ubuntu-latest
       steps: 
          - name: Checkout Repo
            uses: actions/checkout@v4
           
          - name: Docker Registry
            uses: docker/login-action@v3.4.0
            with:
                username: ${{ vars.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD }}   

          - name: Docker Registry Push
            uses: docker/build-push-action@v6
            with:
                context: .
                push: false
                tags: ${{ vars.DOCKER_USERNAME }}/solar-system:${{ github.sha }}  


          - name: Docker Image testing
            run: |
                 docker images
                 docker run --name solar-system -d \
                 -p 3000:3000 \
                 -e MONGO_URI:$MONGO_URI \
                 -e MONGO_USERNAME:$MONGO_USERNAME \
                 -e MONGO_PASSWORD:$MONGO_PASSWORD \
                 ${{ vars.DOCKER_USERNAME }}/solar-system:${{ github.sha }}

                 
          - name: Docker Registry Push
            uses: docker/build-push-action@v6
            with:
              context: .
              push: true
              tags: ${{ vars.DOCKER_USERNAME }}/solar-system:${{ github.sha }} 
              
    dev-deploy:

          needs: docker
          runs-on: ubuntu-latest
          steps:
            - name: Checkout Repo
              uses: actions/checkout@v4

            - name: Install Kubectl
              uses: azure/setup-kubectl@v3
              with:
                 version: 'v1.2.6.0'

            -  name: Setup Kubeconfig
               uses: azure/k8s-setup-context@v3
               with: 
                 method: kubeconfig
                 kubeconfig: ${{ secrets.Kubeconfig }}


            - name: Fetech Kubernetes details
              run: | 
                kubectl version --short
                kubectl get nodes

            - name: Save INGRESS IP address
              run: |
                 echo "INGRESS_IP=$(kubectl -n ingress-nginx get services ingress-nginx-controller -o jsonpath="{.status.loadbalancer.ingress[0].ip}")" >>$GITHUB_ENV

 
           
            - name: Replace token in manifest files
              uses: cschleiden/replace-token@v1
              with: 
                tokenPrefix: '_{_'
                tokenSuffix: '_}_'
                files: '["kubernetes/development/*.yaml"]' 
              env:
                NAMESPACE: ${{ vars.NAMESPACE }}
                REPLICAS: ${{ vars.REPLICAS }}
                IMAGE: ${{ vars.DOCKER_USERNAME }}/solar-system:${{ github.sha }} 
                INGRESS_IP: ${{ env.INGRESS_IP }}
                 
            -  name: Check files
               run: |
                   cat kubernetes/development/*.yaml 

            -  name: Create MongoDB secret
               run: |
                  kubectl -n ${{vars.NAMESPACE }} create secret generic mongo-db-creds \
                  --from-literal=MONGO_URI=${{ env.MONGO_URI }} \
                  --from-literal=MONGO_USERNAME=${{ Vars.MONGO_USERNAME }} \
                  --from-literal=MONGO_PASSWORD=${{ secrets.MONGO_PASSWORD }} \ 
                  --save-config \
                  --dry-run-Client\
                  --o yaml | kubectl apply -f -     

            - name: Deploy to DEV env
              run: |
                 kubectl apply kubernetes/development       
               



        

         

              
          
          

      
           



            
        
